[package]
name = "mdtohtml"
version = "0.1.0"
edition = "2021"
authors = ["kazu.I"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.10.3"
maud = "0.26.0"
clap = { version = "4.5.4", features = ["derive"] }
